### ISSUE TITLE
DebugLog.cpp

### ISSUE THREAD

**Issue by kost-samsonov** [hideakitai/DebugLog#2]
//to avoid multiple declaration issue

    #include <DebugLog.h>
    
namespace arx {
namespace debug {
    
    #ifdef ARDUINO
      Stream* stream {&Serial};
    #endif

    #ifdef ARDUINO      
    Logger* logger {nullptr};
    bool b_auto_save {false};
    bool b_only_sd {false};
    LogLevel log_level = LogLevel::VERBOSE;
    
    #endif
    }
  }

and extern these variables in .h file

**Comment by hideakitai** [comment]
@kost-samsonov Sorry for late reply, fixed in v0.3.0! Thanks.
