### ISSUE TITLE
LOG_ATTACH_FS_AUTO with SD-Card do not work

### ISSUE THREAD

**Issue by DeadOldMan** [hideakitai/DebugLog#4]
When i use the example with an SD-Card the LOG_ATTACH_FS_AUTO() creates a file with size equal to available bytes left on SD-Card.
the content of the file seems to be random.

Version 0.6.0.

When using Verion 0.5.1 (and different interface ) it works fine.

**Comment by hideakitai** [comment]
Hi, thank you for the feedback. Which board and firmware version do you use? Please let me know more about your environment.

**Comment by DeadOldMan** [comment]
Hi,
its a ESP32 Dev Kit with an SPI SD-Card module.
I am using the standard SD lib with "SD.h" include.
Using also Visual Code with PlatformIO extension in the latests versions.
Hope this is enough information.

**Comment by hideakitai** [comment]
Thank you. Can you tell me the version of esp32?  Which example are you using?

**Comment by DeadOldMan** [comment]
I use this one : https://www.ebay.de/itm/174790810396

**Comment by DeadOldMan** [comment]
sorry did not read all of your last post.
Example is log_to_file.ino

**Comment by hideakitai** [comment]
@DeadOldMan Thank you! Probably fixed in v0.6.1. Could you check if it works?

**Comment by DeadOldMan** [comment]
Tested with 0.6.1 and seems to work now.
Thanks.
